datasets: 'braindata'
num_classes: 1
num_parts:
    - 2
input_features_dim: 4
batch_size: 16
num_points: 4096
num_workers: 1
# data augmentation
x_angle_range: 0.2
y_angle_range: 0.2
z_angle_range: 3.1415926
scale_low: 0.95
scale_high: 1.1
noise_std: 0.001
noise_clip: 0.05
translate_range: 0.0

# ---------------------------------------------------------------------------- #
# Model
# ---------------------------------------------------------------------------- #
backbone: 'resnet'
head: 'resnet_part_seg'
radius: 0.5
sampleDl: 0.2
nsamples:
  - 11
  - 25
  - 37
  - 36
  - 33
npoints:
  - 2560
  - 1536
  - 384
  - 128
width: 144
depth: 2
bottleneck_ratio: 2

# ---------------------------------------------------------------------------- #
# Training options
# ---------------------------------------------------------------------------- #
epochs: 500
start_epoch: 1
base_learning_rate: 0.002
lr_scheduler: 'cosine'  # step,cosine
optimizer: 'adamW'
warmup_epoch: -1
lr_decay_steps: 1
lr_decay_rate: 0.9885531
weight_decay: 0.00001
momentum: 0.9

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
load_path: ''
print_freq: 10
save_freq: 10
val_freq: 10
log_dir: './output'
local_rank: 0
amp_opt_level: ''
rng_seed: 0

# ---------------------------------------------------------------------------- #
# Local Aggregation options
# ---------------------------------------------------------------------------- #
local_aggregation_type: 'pospool'
pospool:
  position_embedding: 'xyz'
  reduction: 'avg'
  output_conv: False
